#!/bin/bash

exception () {
  MSG=${1:-"${0} exception"}
  echo "EXCEPTION: $MSG" >&2
  EC="${2:-1}"
  [ "$EC" -eq 2 ] \
    && echo "USAGE: ${0} HOST" >&2
  exit "$EC"
}

iping () {
  ping -c1 -W2 "$1" >/dev/null 2>&1
  SC="$?"
  [ "$SC" -gt 0 ] \
    && echo \
    && echo -n "$(date) $SC " \
    || echo -n "."
  sleep 4
  iping "${1}"
}

[[ -z "${1}" ]] \
  && exception "Missing HOST" 2

iping "${1}"
